Print trailing comma for type parameters
prettier/prettier pull request #10109
Opened 2021-01-23 04:38 UTC by sosukesuzuki

## Description

Fixes #9338. I think we can do this at next major.

## Checklist

- [x] I’ve added tests to confirm my change works.
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

2021-01-26 14:08 UTC, thorn0 commented
TS 2.7 was released 3 years ago. I don't think we need a major version for this.

2021-01-26 14:18 UTC, thorn0 requested changes
This logic relies on the file extension (`isTSXFile`), so I can't reproduce this on the playground:

`test-tsx.tsx`:
```ts
const f = <Tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt, >() => 1
```

```sh
$ prettier test-tsx.tsx --trailing-comma all
const f = <
  Tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt,,
>() => 1;
```

See also https://github.com/prettier/prettier/issues/3662#issuecomment-530540734

BTW, this also means that Prettier has been outputting code with trailing commas in type parameters for a while already, at least for TSX. so this change is definitely safe for a non-major version.

2021-01-27 12:44 UTC, thorn0 commented on src/language-js/print/type-parameters.js
> +      : ifBreak(shouldPrintComma(options, "all") ? "," : "");
Please extract the `shouldPrintComma` condition out of `ifBreak` like I did in `print/array.js`:

https://github.com/prettier/prettier/blob/bba719283d484f27659e2a69ff214cf287f15ab7/src/language-js/print/array.js#L60-L66

2021-01-27 13:24 UTC, thorn0 commented on src/language-js/print/type-parameters.js
> +      ? ifBreak(",", "")
```suggestion
      ? ifBreak(",")
```

2021-01-27 13:28 UTC, thorn0 approved these changes

2021-01-28 13:55 UTC, fisker approved these changes

2021-01-28 14:03 UTC, merged