Update babel/parser to 7.12.17
prettier/prettier pull request #10345
Opened 2021-02-19 00:27 UTC by sosukesuzuki

## Description

Closes #10308 

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

## Todo

Add tests for:

- [ ] babel/babel#12686
- [ ] babel/babel#12684
- [ ] babel/babel#12520
- [ ] babel/babel#12599
- [ ] babel/babel#12562
- [ ] babel/babel#12661
- [ ] babel/babel#12748
- [ ] babel/babel#12735
- [ ] babel/babel#12775
- [ ] babel/babel#12771
- [ ] babel/babel#12763
- [ ] babel/babel#12758
- [ ] babel/babel#12760
- [ ] babel/babel#12776
- [ ] babel/babel#12785

2021-02-21 01:29 UTC, sosukesuzuki commented on tests/typescript/interface/__snapshots__/jsfmt.spec.js.snap
> +  e();
https://github.com/prettier/prettier/issues/9760

2021-02-21 14:21 UTC, fisker commented on tests/js/async/await-keyword.js
> +async (x = await 2) => {};
Can you also test, Note that `flow` parse this differently.

**Prettier pr-10345**
[Playground link](https://deploy-preview-10345--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEBDAzgTymABAMwFccYBLaAiCACgEpdgAdKXA4sMigI1QCdqAHrgC8uVAHdUpGLmoAmWvWABfZqqjMM2PIJFjJ02QvrCAfA2UBuEABoQEAA6co6ZKD68I4gAp8ErlFQAG0lMVzsuXlQwAGs4GABlB2jSKABzZBheQjg7OABbLjgAE2KSgBlUdMJUNLgAMQhefNQYMnTkNEIYCFsQAAsYfKCAdX7pOHRksDgE-2lSADdpTE6wdHCQVPQ4XhhvKLSW5HxgnbsAK3QBACEo2PiE1Hy4ctS4E7PckCuBBNS0kE4ABFQgQeCfILnEDJXg7XidHhFIJ9By8VIwEakYowfrIAAcAAY7GiIDsRlEHJ00ZNdosPnYAI5g+AHRwBNDoAC0UDgJRKfV4cGZpCFB1qxyQpyh3x2+VImWysoBQNB4I+Uq+dhgqC4WJxeKQcm1UVIQQBAGEIPlJSBJgBWPqEHYAFV1AWl0MWOQAklAyrAEmB0U4AIL+hIwTBAyE7ZTKIA)
<!-- prettier-ignore -->
```sh
--parser babel
```

**Input:**
<!-- prettier-ignore -->
```jsx
async function foo() {
  function bar(x = await (2)) {}
}

async (x = await (2)) => {};
```

**Output:**
<!-- prettier-ignore -->
```jsx
async function foo() {
  function bar(x = await(2)) {}
}

async (x = await 2) => {};

```

2021-02-21 14:25 UTC, fisker commented on tests/js/await/out-of-function.js
> +await 0;
`flow` `typescript` `babel` all parse them differently.

**Prettier pr-10345**
[Playground link](https://deploy-preview-10345--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACMAGwEMBnUvAYT2AB0o88M8BePYgd2IEt8AKAAwBKANz0AvvXqce-YSJAAaEBAwxu0UslDFs2CBwAKuhFpTFCXAJ5blAI2zEwAazgwAyhifcoAc2Qw2ACucMpwALZ2cAAm0TEAMsR+QcS+cABiOOHEMOp+yCDEQTAQSiAAFjDhhADq5bxwpF5gcO6mvNwAbrxWBWDkZT6kcLiGjr7ZyABmFsPKAFakaABCji5u7sThcPE+cNOzoSCLaO4+voRwAIpBEPAHhHMgXtjD2AUwVhiNYNjcamUMH9YDVuNEYOVkAAOATKIEQYY1RwYApAxojTr7ZQAR1u8DGqjMhVIAFooHAYjEytg4LjuDSxqlJkgZo8jsNwtwAsF2edLjc7vsWYdlDBiHZQeDIUgAEyixzcQjnSgQcLM1CkACsZSCwwAKuKzKynp0QgBJKBxWDuX7-GAAQUt7k+lwew3E4iAA)
<!-- prettier-ignore -->
```sh
--parser typescript
```

**Input:**
<!-- prettier-ignore -->
```tsx
export class C {
  p = await (0);
}

await (0);
```

**Output:**
<!-- prettier-ignore -->
```tsx
export class C {
  p = await(0);
}

await 0;

```

2021-02-21 14:26 UTC, fisker requested changes
Let's add parenthesized await for all those cases in this PR, we don't need care how it formatted, just to have a snapshot record.

2021-02-21 14:33 UTC, fisker commented on tests/typescript/keywords/__snapshots__/jsfmt.spec.js.snap
> +"Unexpected token, expected \\"{\\" (9:12)
Can we move code of `module Y3` a separate file?

2021-02-25 05:08 UTC, sosukesuzuki commented
@fisker Have we the way to test with only `typescript` parser(not `babel-ts`)?

2021-02-25 06:26 UTC, fisker commented
I think your solution is the best.

2021-02-25 06:32 UTC, fisker commented
@sosukesuzuki The AST compare tests are failing.

2021-02-25 08:31 UTC, fisker approved these changes
Nice job!

2021-02-25 08:41 UTC, fisker commented
@sosukesuzuki You already print `declare`  and `readonly` in `ClassMethod`, can you check if this still needed?
 https://github.com/prettier/prettier/blob/285c15ef08a7422dc31eedcd206680ac582ce1da/src/language-js/clean.js#L201

2021-02-25 09:44 UTC, sosukesuzuki commented
@fisker Maybe we can remove it. But somehow all tests are passed  without it in even `main` branch.

2021-02-25 10:07 UTC, fisker commented
IDK, I added in #9768 because tests failed.

2021-02-25 10:28 UTC, merged