Redirect community plugins
prettier/prettier pull request #12443
Opened 2022-03-13 10:30 UTC by Harry-Hopkinson

## Description

Redirect community plugins. Fix for #12431

## Checklist

- [x] I’ve added tests to confirm my change works.
- [x] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

2022-03-13 16:01 UTC, fisker commented
Can you focus one thing on one PR?

2022-03-13 16:06 UTC, Harry-Hopkinson commented
Sure

2022-03-13 16:13 UTC, fisker requested changes

2022-03-13 16:13 UTC, fisker commented on website/data/languages.yml
> +  nameLink: https://prettier.io/docs/en/plugins.html#community-plugins
```suggestion
  nameLink: ./docs/en/plugins.html#community-plugins
``

2022-03-13 16:13 UTC, fisker commented on website/data/languages.yml
> +    - "[And more...](https://prettier.io/docs/en/plugins.html#community-plugins)"
```suggestion
    - "[And more...](./docs/en/plugins.html#community-plugins)"
```

2022-03-13 16:13 UTC, fisker commented on website/data/languages.yml
> +  nameLink: https://www.javascript.com/
```suggestion
```

2022-03-13 16:13 UTC, fisker commented on website/data/languages.yml
> +  nameLink: "https://www.markdownguide.org/getting-started/"
```suggestion
```

2022-03-13 16:25 UTC, fisker approved these changes
LGTM, thank you!

2022-03-13 16:38 UTC, Harry-Hopkinson commented
Thank you very much 😄

2022-03-13 16:41 UTC, fisker commented
To the reviewer who merge this: Please clean up the commit message when merging.

2022-03-14 08:55 UTC, kachkaev approved these changes

2022-03-14 09:02 UTC, merged