Print the number of files that need formatting.
prettier/prettier pull request #12561
Opened 2022-03-30 16:23 UTC by Harry-Hopkinson

## Description

This change prints the number of files that need to be changed in order to match the Prettier Code Style.

For example if you
```shell
prettier --check <a directory>
```

Now if one file needs to be changed it prints out.
Code style issues found in the above file. Forgot to run Prettier?

Instead of
Code style issues found in the above file(s). Forgot to run Prettier?

Another change is it now prints out the number of files that need to be formatted. For example if you have three files that need to be formatted in a directory it now outputs the number of files that need to change.

```shell
Code style issues found in 3 files. Forgot to run Prettier?"
```

This is in contrast to the previous

```shell
Code style issues fixed in the above file(s). Forgot to run Prettier.
```

## Checklist

- [x] I’ve added tests to confirm my change works.
- [x] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

2022-03-31 11:29 UTC, fisker commented
I like the idea, can you add test for multiple unformatted files?

2022-03-31 20:23 UTC, Harry-Hopkinson commented
The tests work as expected. It outputs the following...
```shell
Code style issues found in 2 files. Forgot to run Prettier?
```

2022-04-01 06:30 UTC, fisker requested changes

2022-04-01 06:30 UTC, fisker commented on src/cli/format.js
> +          ? "Code style issues fixed in the above file(s)."
```suggestion
          ? "Code style issues fixed in the above file."
```

2022-04-01 06:30 UTC, fisker commented on src/cli/format.js
>            ? "Code style issues fixed in the above file(s)."
```suggestion
          ? "Code style issues found in " + numberOfUnformattedFilesFound +" files."
```

2022-04-01 06:31 UTC, fisker commented
Don't merge main into your PR, if it's necessary, we'll ask you to do.

2022-04-01 06:32 UTC, Harry-Hopkinson commented
Okay thanks.

2022-04-01 06:32 UTC, Harry-Hopkinson commented
Just updating the tests.

2022-04-01 07:43 UTC, fisker commented
Can you add changelog for this?

2022-04-01 12:08 UTC, Harry-Hopkinson commented
Sure thing

2022-04-02 07:00 UTC, Harry-Hopkinson commented
@fisker I have now followed the template.

2022-04-02 07:16 UTC, fisker approved these changes
Thanks! I hope no one uses the stderr directly.

2022-04-02 07:17 UTC, Harry-Hopkinson commented
Thank you

2022-04-02 17:38 UTC, sosukesuzuki approved these changes

2022-04-07 00:54 UTC, sosukesuzuki commented
Can we merge this? @fisker Do you have other tasks that is should be done in this PR?

2022-04-07 01:47 UTC, merged

2022-04-07 01:47 UTC, fisker commented
Thank you for contributing to Prettier! ❤️