Remove `prefer-ast-path-node` and add `prefer-ast-path-getters`
prettier/prettier pull request #13648
Opened 2022-10-15 12:46 UTC by sosukesuzuki

## Description

Removes `prefer-ast-path-node` internal ESLint rule.
Adds `prefer-ast-path-getters` that supports `path.node`, `path.parent` and `path.grandparent`.

## Checklist

- [x] I’ve added tests to confirm my change works.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

2022-10-17 02:21 UTC, fisker requested changes

2022-10-17 02:21 UTC, fisker commented on scripts/tools/eslint-plugin-prettier-internal-rules/prefer-ast-path-getters.js
> +      [messageId]: "Prefer {{ getter }} instead of {{ method }}.",
```suggestion
      [messageId]: "Prefer {{ getter }} over {{ method }}.",
```

2022-10-17 02:21 UTC, fisker commented on scripts/tools/eslint-plugin-prettier-internal-rules/prefer-ast-path-getters.js
> +              node.property.range[1] + 2 + argumentsLength,
```suggestion
              // remove `()` for CallExpression
              node.range[1],
```

We don't need make it 100% safe for edge cases, but this change will make the fix much safer,  user may add comments to explain the argument or code is not formatted.

```js
path.getParentNode(
) // <- not formatted.
```

```js
path.getParentNode(/* comment */ 1 )
```

2022-10-17 02:21 UTC, fisker commented on scripts/tools/eslint-plugin-prettier-internal-rules/prefer-ast-path-getters.js
> +          method: getterMethodMap.get(getterName),
Let's use `node.property.name` to make the message more clear.

2022-10-17 02:21 UTC, fisker commented on scripts/tools/eslint-plugin-prettier-internal-rules/prefer-ast-path-getters.js
> +          getter: `\`path.${getterName}\``,
Move `path.` to message template, and use `AstPath#{{getter}}`.

2022-10-17 02:21 UTC, fisker commented on scripts/tools/eslint-plugin-prettier-internal-rules/prefer-ast-path-getters.js
> +        const propertyName = node.property?.name;
```suggestion
        const propertyName = node.property.name;
```

2022-10-17 02:23 UTC, fisker commented on scripts/tools/eslint-plugin-prettier-internal-rules/prefer-ast-path-getters.js
> +            report(node, callExprArguments.length, "parent");
```suggestion
          if (
          	// path.getParentNode()
          	callExprArguments.length === 0 || 
          	// path.getParentNode(0)
          	callExprArguments[0].value === 0
         ) {
            report(node, callExprArguments.length, "parent");
```

2022-10-17 12:54 UTC, sosukesuzuki commented
@fisker Thank you for your reviewing! I've fixed and refctored.

2022-10-17 14:43 UTC, fisker reviewed
nitpock

2022-10-17 14:43 UTC, fisker commented on scripts/tools/eslint-plugin-prettier-internal-rules/prefer-ast-path-getters.js
> +  "> MemberExpression",
```suggestion
  "> MemberExpression.callee",
```

2022-10-17 14:43 UTC, fisker commented on scripts/tools/eslint-plugin-prettier-internal-rules/prefer-ast-path-getters.js
> +  return node.object?.name?.toLowerCase().endsWith("path");
MemberExpression's object can't be nullish.

2022-10-17 14:43 UTC, fisker commented on scripts/tools/eslint-plugin-prettier-internal-rules/prefer-ast-path-getters.js
> +  return node.object?.name?.toLowerCase().endsWith("path");
If we add `Identifier` check to the `MemeberExpression` selector, then the name can't be nullish either.

2022-10-17 14:43 UTC, fisker commented on scripts/tools/eslint-plugin-prettier-internal-rules/prefer-ast-path-getters.js
> +            // path.getParentNode()
Outdated comment.

2022-10-18 02:45 UTC, fisker approved these changes

2022-10-18 03:21 UTC, sosukesuzuki commented on scripts/tools/eslint-plugin-prettier-internal-rules/prefer-ast-path-getters.js
> +  "[callee.object.name=/[pP]ath$/]",
Great query

2022-10-18 05:23 UTC, merged