Fix to add parentheses for TSTypeQuery in some case
prettier/prettier pull request #14042
Opened 2022-12-21 13:24 UTC by onishi-kohei

## Description
Fix to add parentheses for TSTypeQuery in some case (#13546)

I added an if statement with the parent type the example sentence had.
``` js
a as (typeof node.children)[number]

a as (typeof node.children)[]

a as ((typeof node.children)[number])[]
````

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

2022-12-23 12:19 UTC, fisker commented
Need add tests https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md#tests

2022-12-25 17:07 UTC, thorn0 commented on tests/format/typescript/typeof/typeof.ts
> +// https://github.com/typescript-eslint/typescript-eslint/pull/4382
Please remove this comment

2022-12-25 17:08 UTC, thorn0 commented
Please add a changelog entry. See https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md#other

2022-12-26 00:00 UTC, onishi-kohei commented
I am grateful to @thorn0  and @fisker for their support.

2022-12-29 02:37 UTC, fisker requested changes

2022-12-29 02:37 UTC, fisker commented on src/language-js/needs-parens.js
> +    // fallthrough
I don't think `TSTypeQuery`(TypeScript node type) can be a child of `NullableTypeAnnotation`(flow node type). This should not fallthrough.

2022-12-29 04:53 UTC, onishi-kohei commented on src/language-js/needs-parens.js
> +      }
```js
a as (typeof node.children)[]
```
this property name was `elementType`
May I add a case like the code below?

’’’ js
return (
        name === "objectType" || name === "elementType"   &&
        (parent.type === "TSIndexedAccessType" || parent.type === "TSArrayType")
      )
'''

2022-12-29 05:46 UTC, fisker commented on src/language-js/needs-parens.js
> +      }
No, should be 

```js
return (
        (name === "objectType" && parent.type === "TSArrayType")&&
        (name === "elementType" && parent.type === "TSIndexedAccessType" )
      )
```

2022-12-29 06:20 UTC, sosukesuzuki reviewed
LGTM except for the review comments that remain now.

2022-12-29 07:08 UTC, onishi-kohei commented on src/language-js/needs-parens.js
> +      }
Fixed in this commit.　https://github.com/prettier/prettier/pull/14042/commits/70353171ed013c8e40b0a425d7d8b927ea690bbc

2022-12-29 07:10 UTC, fisker approved these changes
Thanks for working on this.

2022-12-30 06:04 UTC, sosukesuzuki approved these changes

2022-12-30 06:05 UTC, merged

2022-12-30 06:30 UTC, fisker commented
@onishi-kohei  

There should be other cases need add parens, for example:

```js
a as (typeof node.children)!
```

if you are interested [thoses types in this branch](https://github.com/prettier/prettier/blob/369bf2a1c117bdf4346e851d1039d6d2b014e160/src/language-js/needs-parens.js#L500) may give you the idea to improve.

And don't send PRs from your `main` branch next time.

2023-01-17 23:58 UTC, SamuelMS commented
@onishi-kohei Does this interact cleanly with `keyof typeof`? I'm seeing new errors in `2.8.3`:

```typescript
{
  // ...
  accept: typeof MIME_TYPES[keyof typeof MIME_TYPES][];
}
```

> ```14:11  Error: Replace `typeof·MIME_TYPES` with `(typeof·MIME_TYPES)`  prettier/prettier```

The type is ugly but is tied to a third-party library. Parentheses that are added by hand are stripped by prettier automatically.

2023-01-18 13:55 UTC, onishi-kohei commented
@SamuelMS 
I have verified that the following code did not generate an error.
``` js
// Input
export type A = {
  a?: {
    [
      x: string
    ]: typeof SomeLongLongLongTypeName[keyof typeof SomeLongLongLongTypeName];
  } | null;
};
```

2023-01-18 14:03 UTC, thorn0 commented
@SamuelMS Make sure you don't have a caret (`^`) in front of Prettier's version in your `package.json`. See https://prettier.io/docs/en/install.html#summary

2023-01-27 02:18 UTC, zomars commented
Can we disable this option?

2023-02-03 06:17 UTC, SamuelMS commented
@onishi-kohei You're right, this was an environment issue – IDEA silently persisted a cached version of an older version of prettier around.