Add `prettier-plugin-sort-json` community plugin
prettier/prettier pull request #14041
Opened 2022-12-20 23:08 UTC by Gudahtt

## Description

The Prettier plugin `prettier-plugin-sort-json` has been added to the community plugin list. This plugin sorts JSON files.

## Checklist

- [x] I’ve added tests to confirm my change works.
- [x] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

2022-12-22 01:29 UTC, fisker approved these changes

2022-12-22 20:22 UTC, kachkaev requested changes
I thought we decided to not advertise plugins like this 🤔

2022-12-22 21:27 UTC, Gudahtt commented
Feel free to not include this plugin. I was not aware this was against the intended purpose of the plugin API. I am aware Prettier is just for formatting, but didn't realize that using plugins for other things was discouraged.

The linked discussion suggests that there is a desire to implement these type of rules in ESLint instead, but ESLint does not support JSON. There is a plugin, but I've found it to be slow and lacking in features, and [even the plugin author doesn't think it's especially well suited for the task](https://github.com/azeemba/eslint-plugin-json#is-eslint-really-the-best-tool-to-lint-my-json). Prettier's plugin API is the easiest way to lint JSON files in JavaScript projects today.

2023-09-01 11:53 UTC, Gudahtt commented
Still seems like there has been no decision here. Any thoughts - is this good, or should this be closed?

The plugin has recently been updated to support Prettier v3.

2025-01-06 18:13 UTC, Gudahtt commented
@kachkaev and @fisker, is there anyone in particular you're waiting on to review this decision? I would appreciate it if you could come to some decision one way or the other, and either merge or close this PR 🙏

2025-01-08 01:31 UTC, fisker commented
Sorry, for reason mentioned in https://github.com/prettier/prettier/pull/14041#pullrequestreview-1228220408, we decide to close this.

2025-01-08 01:31 UTC, closed without merging