Switch `kRegex` to use RegExp with `u` directly
prettier/prettier pull request #15584
Opened 2023-11-01 15:45 UTC by fisker

## Description

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

2023-11-03 06:22 UTC, sosukesuzuki approved these changes

2023-11-03 06:29 UTC, sosukesuzuki requested changes
CI is failed

2023-11-03 11:40 UTC, fisker commented
Something wrong with the `g` flag.

2023-11-12 16:00 UTC, fisker commented
I don't know what am I thinking, I was wrong, there should be no `g`... And I made the same mistake in angular-estree-parser https://github.com/prettier/angular-estree-parser/pull/266

2023-11-12 16:25 UTC, merged