feat: add support for `package.yaml` config
prettier/prettier pull request #16157
Opened 2024-03-19 00:27 UTC by danielbayley

## Description

Enable support for reading `prettier` configuration directly from [`package.yaml`](https://github.com/pnpm/pnpm/pull/1799).

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [x] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

2024-03-19 03:02 UTC, sosukesuzuki commented
I did not know this pnpm feature. Is there any official documentation? Or are there other tools besides pnpm that support this format?

2024-03-19 03:45 UTC, danielbayley commented
> Is there any official documentation?

@sosukesuzuki See https://github.com/pnpm/pnpm.io/issues/487.

> are there other tools besides pnpm that support this format?

Support has already been added to [lint-staged](https://github.com/lint-staged/lint-staged/pull/1344), [cosmiconfig](https://github.com/cosmiconfig/cosmiconfig/releases/tag/v9.0.0), and [commitlint](https://github.com/conventional-changelog/commitlint/pull/3976), so far…

2024-04-04 14:18 UTC, fisker commented
So, we have to support `package.json5` too?

2024-04-04 14:31 UTC, fisker commented
> that would be for a separate PR anyway…

Sounds good.

2024-04-10 20:22 UTC, fisker commented on src/config/prettier-config/config-searcher.js
> +  "package.yml",
Please remove it,we can add support for it after pnpm supports it.

2024-04-10 20:23 UTC, fisker commented on changelog_unreleased/yaml/16157.md
> +#### Add support for `package.yaml` config (#16157 by @danielbayley)
This should be in `api/` directory.

2024-04-11 03:01 UTC, fisker requested changes

2024-04-11 03:01 UTC, fisker commented on src/config/prettier-config/config-searcher.js
> +  if (/^package.ya?ml$/.test(name)) {
1

2024-04-11 03:01 UTC, fisker commented on src/config/prettier-config/load-config.js
> +      : /^package.ya?ml$/.test(fileName)
2

2024-04-11 15:02 UTC, fisker approved these changes

2024-05-10 09:21 UTC, fisker requested changes
Just noticed there is no test for it yet.

2024-05-10 10:36 UTC, merged